version: "3.8"

services: 
	backend:
		build: 
			context: ./backend
			dockerfile: Dockerfile
		hostname: backend
		ports: 
			- 8000:8000
		env_file: ./env/.env
		volumes: 
			- ./backend:/code:rw
		command:  >
			sh -c "python manage.py runserver 0.0.0.0:8000"
		depends_on: 
			- db


	frontend:
		build: 
			context: ./frontend
			dockerfile: Dockerfile
		ports: 
			- 8080:8080
		volumes: 
			- ./frontend:/app:rw
		# depends on backend
		restart: on-failure
		environment: 
			- CHOKIDAR_USEPOLLING=true


	db:
		image: postgres:latest
		hostname: db
		volumes: 
			- postgres_data:/var/lib/postgresql/data/
		environment: 
			- POSTGRES_USER=gabriel
			- POSTGRES_DB=lor_db
			- POSTGRES_PASSWORD=devpass1234
			- POSTGRES_HOST=db
			- POSTGRES_PORT=5432
		ports: 
			- 5432


volumes: 
	postgres_data: